name: adoptAmigo
adescription: A new Flutter project.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  firebase_ui_auth: ^1.13.1
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.16.1
  animate_do: ^3.3.4
  uuid: ^4.4.0
  intl: ^0.18.1
  fluttertoast: ^8.2.4
  provider: ^6.0.1 
  flutter_launcher_icons: "^0.13.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.jpg"

